# fly.toml app configuration file generated for fal-bot-chris on 2025-10-08T15:58:21-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fal-bot-chris'
primary_region = 'sjc'

[build]


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

